import {
  CustomPlanDailyRecord,
  CustomPlanSubject,
  CustomPlanTask,
  CustomPlanUnit,
  CustomStudyPlan,
  Quality
} from "@/types/study";
import { daysUntil, todayKey } from "@/lib/date";
import { clamp, uid } from "@/lib/utils";

export interface CustomPlanBlueprint {
  title: string;
  goal: string;
  targetDate: string;
  subjects: Array<{ name: string; color?: string }>;
  units: Array<{
    subjectName: string;
    title: string;
    resource: string;
    focus: string;
    practice: string;
    estimatedDays?: number;
  }>;
  strategy: string[];
}

const subjectColors = ["#2563eb", "#7c3aed", "#16a34a", "#f97316", "#0891b2", "#db2777"];

export function createCustomPlanFromBlueprint(blueprint: CustomPlanBlueprint): CustomStudyPlan {
  const now = new Date().toISOString();
  const subjects: CustomPlanSubject[] = blueprint.subjects.slice(0, 8).map((subject, index) => ({
    id: uid("plan-subject"),
    name: subject.name || `科目${index + 1}`,
    color: subject.color || subjectColors[index % subjectColors.length]
  }));
  const fallbackSubject = subjects[0] ?? { id: uid("plan-subject"), name: "综合", color: subjectColors[0] };
  const normalizedSubjects = subjects.length > 0 ? subjects : [fallbackSubject];

  const units: CustomPlanUnit[] = blueprint.units.slice(0, 80).map((unit) => {
    const subject = normalizedSubjects.find((item) => item.name === unit.subjectName) ?? fallbackSubject;
    return {
      id: uid("plan-unit"),
      subjectId: subject.id,
      title: unit.title || "学习单元",
      resource: unit.resource || "自定义资料",
      focus: unit.focus || "完成本单元核心内容。",
      practice: unit.practice || "完成配套练习并记录错因。",
      estimatedDays: Math.max(1, Math.min(14, Number(unit.estimatedDays) || 1)),
      completed: false
    };
  });

  return {
    id: uid("plan"),
    title: blueprint.title || "新的学习规划",
    goal: blueprint.goal || "完成新的学习目标",
    targetDate: blueprint.targetDate || todayKey(),
    createdAt: now,
    updatedAt: now,
    paused: false,
    subjects: normalizedSubjects,
    units,
    records: {},
    strategy: blueprint.strategy?.slice(0, 8) ?? []
  };
}

export function getCustomPlanCompletion(plan: CustomStudyPlan) {
  if (plan.units.length === 0) return 0;
  return (plan.units.filter((unit) => unit.completed).length / plan.units.length) * 100;
}

export function getCustomPlanTodayRecord(plan: CustomStudyPlan, date = todayKey()) {
  return plan.records[date];
}

export function getNextUnits(plan: CustomStudyPlan, limit = 3) {
  return plan.units.filter((unit) => !unit.completed).slice(0, limit);
}

export function generateCustomPlanRecord(plan: CustomStudyPlan, date = todayKey()): CustomPlanDailyRecord {
  const now = new Date().toISOString();
  const daysLeft = Math.max(daysUntil(plan.targetDate), 1);
  const remainingUnits = plan.units.filter((unit) => !unit.completed);
  const dailyUnitCount = Math.max(1, Math.min(3, Math.ceil(remainingUnits.length / daysLeft)));
  const units = remainingUnits.slice(0, dailyUnitCount);
  const tasks: CustomPlanTask[] = [];

  units.forEach((unit, index) => {
    const subject = plan.subjects.find((item) => item.id === unit.subjectId);
    const startTimes = ["09:00-10:20", "14:00-15:20", "19:30-20:30"];
    tasks.push({
      id: uid("plan-task"),
      date,
      time: startTimes[index] ?? "自定义",
      subjectId: unit.subjectId,
      title: `${subject?.name ?? "综合"}：${unit.title} - ${unit.focus}`,
      plannedMinutes: index === 0 ? 80 : 60,
      completed: false,
      actualMinutes: index === 0 ? 80 : 60,
      quality: "",
      note: "",
      unitId: unit.id,
      autoGenerated: true
    });
    tasks.push({
      id: uid("plan-task"),
      date,
      time: index === 0 ? "20:30-21:10" : "碎片时间",
      subjectId: unit.subjectId,
      title: `练习闭环：${unit.practice}`,
      plannedMinutes: 40,
      completed: false,
      actualMinutes: 40,
      quality: "",
      note: "",
      unitId: unit.id,
      autoGenerated: true
    });
  });

  tasks.push({
    id: uid("plan-task"),
    date,
    time: "21:40-22:00",
    subjectId: plan.subjects[0]?.id ?? "review",
    title: "今日复盘：记录卡点、未完成原因和明日调整",
    plannedMinutes: 20,
    completed: false,
    actualMinutes: 20,
    quality: "",
    note: "",
    autoGenerated: true
  });

  return {
    date,
    tasks,
    summary: "",
    suggestion: plan.paused
      ? "该规划已暂停，继续后会按照目标日期和当前进度重新生成任务。"
      : "按当前目标日期和未完成单元自动生成，可手动调整任务。",
    createdAt: now,
    updatedAt: now
  };
}

export function ensureCustomPlanRecord(plan: CustomStudyPlan, date = todayKey()) {
  if (plan.paused || plan.records[date]) return plan;
  return {
    ...plan,
    records: {
      ...plan.records,
      [date]: generateCustomPlanRecord(plan, date)
    }
  };
}

export function getCustomPlanRecordRate(record?: CustomPlanDailyRecord) {
  if (!record || record.tasks.length === 0) return 0;
  return (record.tasks.filter((task) => task.completed).length / record.tasks.length) * 100;
}

export function saveCustomPlanRecord(plan: CustomStudyPlan, record: CustomPlanDailyRecord) {
  const now = new Date().toISOString();
  const completedUnitIds = new Set(record.tasks.filter((task) => task.completed && task.unitId).map((task) => task.unitId));
  const updatedUnits = plan.units.map((unit) =>
    completedUnitIds.has(unit.id) ? { ...unit, completed: true, completedAt: unit.completedAt ?? now } : unit
  );
  const rate = Math.round(getCustomPlanRecordRate(record));
  const savedRecord: CustomPlanDailyRecord = {
    ...record,
    savedAt: now,
    updatedAt: now,
    suggestion:
      rate >= 85
        ? "今日完成度较好，可以继续按该规划推进。"
        : rate < 60
          ? "今日完成偏低，明天会优先保留未完成单元，不建议盲目增加新内容。"
          : "今日完成一般，建议明天保留一个复盘任务并完成未闭环练习。"
  };

  return {
    ...plan,
    units: updatedUnits,
    records: {
      ...plan.records,
      [record.date]: savedRecord
    },
    updatedAt: now
  };
}

export function updateCustomPlanRecord(
  plan: CustomStudyPlan,
  date: string,
  updater: (record: CustomPlanDailyRecord) => CustomPlanDailyRecord
) {
  const record = plan.records[date] ?? generateCustomPlanRecord(plan, date);
  return {
    ...plan,
    records: {
      ...plan.records,
      [date]: updater(record)
    },
    updatedAt: new Date().toISOString()
  };
}

export function setCustomPlanPaused(plan: CustomStudyPlan, paused: boolean) {
  const now = new Date().toISOString();
  if (paused) {
    return {
      ...plan,
      paused: true,
      pausedAt: now,
      updatedAt: now
    };
  }

  const resumedPlan = {
    ...plan,
    paused: false,
    resumedAt: now,
    updatedAt: now
  };
  const date = todayKey();
  const current = resumedPlan.records[date];
  const untouched =
    !current ||
    (!current.savedAt &&
      current.tasks.every((task) => task.autoGenerated && !task.completed && task.actualMinutes === task.plannedMinutes && !task.note));

  if (!untouched) return resumedPlan;
  return {
    ...resumedPlan,
    records: {
      ...resumedPlan.records,
      [date]: generateCustomPlanRecord(resumedPlan, date)
    }
  };
}

export function customPlanMinutes(record?: CustomPlanDailyRecord) {
  return record?.tasks.reduce((sum, task) => sum + (Number(task.actualMinutes) || 0), 0) ?? 0;
}

export function qualityOrEmpty(value: string): Quality {
  return value === "很好" || value === "一般" || value === "较差" ? value : "";
}

export function boundedProgress(value: number) {
  return Math.round(clamp(value));
}

