export type Subject = "math" | "cs408" | "english" | "review";

export type Quality = "" | "很好" | "一般" | "较差";

export interface StudyTask {
  id: string;
  date: string;
  time: string;
  subject: Subject;
  title: string;
  plannedMinutes: number;
  completed: boolean;
  actualMinutes: number;
  quality: Quality;
  note: string;
  autoGenerated?: boolean;
}

export interface DailyRecord {
  date: string;
  tasks: StudyTask[];
  summary: string;
  suggestion: string;
  adjustmentMessages: string[];
  createdAt: string;
  updatedAt: string;
  savedAt?: string;
}

export interface MathProgress {
  currentLecture: number;
  calculusDone: boolean;
  linearStarted: boolean;
  linearUnit: number;
  linearDone: boolean;
  probabilityStarted: boolean;
  probabilityUnit: number;
  probabilityDone: boolean;
  zhangyu1000Done: number;
  mistakeCount: number;
}

export interface Cs408Progress {
  dataStructureStatus: "已学完" | "复习中" | "未开始";
  dataStructureExerciseRate: number;
  osChapter: number;
  osDone: boolean;
  coaChapter: number;
  coaDone: boolean;
  networkChapter: number;
  networkDone: boolean;
  wangdaoExerciseRate: number;
}

export interface EnglishProgress {
  wordDays: number;
  sentenceCount: number;
  readingStartDate: string;
  readingStarted: boolean;
  readingPassages: number;
  newWords: number;
}

export interface ProgressState {
  math: MathProgress;
  cs408: Cs408Progress;
  english: EnglishProgress;
}

export interface Settings {
  targetDate: string;
  dailyStudyHours: number;
  darkMode: boolean;
}

export interface CloudSyncState {
  enabled: boolean;
  autoSync: boolean;
  lastSyncedAt?: string;
  lastPulledAt?: string;
  lastError?: string;
}

export interface AdjustmentLog {
  id: string;
  date: string;
  message: string;
  createdAt: string;
}

export type WeakPointStatus = "待复盘" | "复盘中" | "已掌握";

export interface WeakPoint {
  id: string;
  date: string;
  subject: Subject;
  title: string;
  source: string;
  status: WeakPointStatus;
  reviewCount: number;
  nextReviewDate: string;
  lastReviewedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface AppState {
  version: number;
  records: Record<string, DailyRecord>;
  progress: ProgressState;
  settings: Settings;
  cloudSync: CloudSyncState;
  adjustmentLogs: AdjustmentLog[];
  weakPoints: WeakPoint[];
}

export interface SubjectStat {
  subject: Subject;
  total: number;
  completed: number;
  rate: number;
  minutes: number;
}
