export type Subject = "math" | "cs408" | "english" | "review";

export type Quality = "" | "很好" | "一般" | "较差";

export type StudyPhase = "first" | "second" | "sprint";

export type TaskStatus = "todo" | "partial" | "done";

export interface StudyTask {
  id: string;
  date: string;
  time: string;
  subject: Subject;
  title: string;
  plannedMinutes: number;
  completed: boolean;
  status?: TaskStatus;
  actualMinutes: number;
  quality: Quality;
  note: string;
  autoGenerated?: boolean;
}

export interface DailyRecord {
  date: string;
  tasks: StudyTask[];
  summary: string;
  suggestion: string;
  adjustmentMessages: string[];
  phase?: StudyPhase;
  createdAt: string;
  updatedAt: string;
  savedAt?: string;
  progressAppliedTaskIds?: string[];
  pendingProgressTaskIds?: string[];
}

export interface MathProgress {
  currentLecture: number;
  calculusDone: boolean;
  linearStarted: boolean;
  linearUnit: number;
  linearDone: boolean;
  probabilityStarted: boolean;
  probabilityUnit: number;
  probabilityDone: boolean;
  zhangyu1000Done: number;
  mistakeCount: number;
}

export interface Cs408Progress {
  dataStructureStatus: "已学完" | "复习中" | "未开始";
  dataStructureExerciseRate: number;
  osChapter: number;
  osDone: boolean;
  coaChapter: number;
  coaDone: boolean;
  networkChapter: number;
  networkDone: boolean;
  wangdaoExerciseRate: number;
}

export interface EnglishProgress {
  wordDays: number;
  sentenceCount: number;
  readingStartDate: string;
  readingStarted: boolean;
  readingPassages: number;
  newWords: number;
}

export interface ProgressState {
  math: MathProgress;
  cs408: Cs408Progress;
  english: EnglishProgress;
}

export interface Settings {
  targetDate: string;
  dailyStudyHours: number;
  darkMode: boolean;
  studyPhase: StudyPhase;
}

export interface CloudSyncState {
  enabled: boolean;
  autoSync: boolean;
  lastSyncedAt?: string;
  lastPulledAt?: string;
  lastError?: string;
}

export interface AdjustmentLog {
  id: string;
  date: string;
  message: string;
  createdAt: string;
}

export type WeakPointStatus = "待复盘" | "复盘中" | "已掌握";

export interface WeakPoint {
  id: string;
  date: string;
  subject: Subject;
  title: string;
  source: string;
  status: WeakPointStatus;
  reviewCount: number;
  nextReviewDate: string;
  lastReviewedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface AppState {
  version: number;
  records: Record<string, DailyRecord>;
  progress: ProgressState;
  settings: Settings;
  cloudSync: CloudSyncState;
  adjustmentLogs: AdjustmentLog[];
  weakPoints: WeakPoint[];
  customPlans: CustomStudyPlan[];
}

export interface SubjectStat {
  subject: Subject;
  total: number;
  completed: number;
  partial: number;
  todo: number;
  rate: number;
  minutes: number;
}

export interface CustomPlanSubject {
  id: string;
  name: string;
  color: string;
}

export interface CustomPlanUnit {
  id: string;
  subjectId: string;
  title: string;
  resource: string;
  focus: string;
  practice: string;
  estimatedDays: number;
  completed: boolean;
  completedAt?: string;
}

export interface CustomPlanTask {
  id: string;
  date: string;
  time: string;
  subjectId: string;
  title: string;
  plannedMinutes: number;
  completed: boolean;
  actualMinutes: number;
  quality: Quality;
  note: string;
  unitId?: string;
  autoGenerated?: boolean;
}

export interface CustomPlanDailyRecord {
  date: string;
  tasks: CustomPlanTask[];
  summary: string;
  suggestion: string;
  createdAt: string;
  updatedAt: string;
  savedAt?: string;
}

export interface CustomStudyPlan {
  id: string;
  title: string;
  goal: string;
  targetDate: string;
  createdAt: string;
  updatedAt: string;
  paused: boolean;
  pausedAt?: string;
  resumedAt?: string;
  subjects: CustomPlanSubject[];
  units: CustomPlanUnit[];
  records: Record<string, CustomPlanDailyRecord>;
  strategy: string[];
}
