import { useEffect, useState } from "react";
import { CheckCircle2, Plus, RotateCcw, Save, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Progress } from "@/components/ui/progress";
import { DailyRecord, Quality, StudyTask, Subject, TaskStatus } from "@/types/study";
import { displayDate } from "@/lib/date";
import {
  getCompletionRate,
  getSubjectStats,
  getTaskStatus,
  isTaskDone,
  isTaskPartial,
  phaseMeta,
  subjectMeta,
  taskHasUnfinishedSignal
} from "@/lib/studyData";
import { cn, percent, uid } from "@/lib/utils";

interface CheckinPageProps {
  record?: DailyRecord;
  selectedDate: string;
  onDateChange: (date: string) => void;
  onCreateRecord: () => void;
  onRegenerateRecord: () => void;
  onChange: (record: DailyRecord) => void;
  onSave: () => void;
}

const subjectOptions: Subject[] = ["math", "cs408", "english", "review"];
const qualityOptions: Quality[] = ["", "很好", "一般", "较差"];
const taskStatusOptions: Array<{ value: TaskStatus; label: string; title: string }> = [
  { value: "todo", label: "未", title: "未完成，系统会优先续补" },
  { value: "partial", label: "部分", title: "部分完成，保留学习时长但不推进进度" },
  { value: "done", label: "完成", title: "已完整完成，可计入进度" }
];

export function CheckinPage({
  record,
  selectedDate,
  onDateChange,
  onCreateRecord,
  onRegenerateRecord,
  onChange,
  onSave
}: CheckinPageProps) {
  const [saveFeedbackAt, setSaveFeedbackAt] = useState("");
  const completionRate = getCompletionRate(record);
  const stats = getSubjectStats(record);
  const sortedTasks = [...(record?.tasks ?? [])].sort((a, b) => a.time.localeCompare(b.time));
  const savedAtText = record?.savedAt
    ? new Date(record.savedAt).toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit", second: "2-digit" })
    : "";

  useEffect(() => {
    setSaveFeedbackAt("");
  }, [selectedDate]);

  useEffect(() => {
    if (record?.savedAt && record.updatedAt > record.savedAt) {
      setSaveFeedbackAt("");
    }
  }, [record?.savedAt, record?.updatedAt]);

  function updateTask(taskId: string, patch: Partial<StudyTask>) {
    if (!record) return;
    const previousTask = record.tasks.find((task) => task.id === taskId);
    const nextStatusFromPatch = patch.status;
    const inferredPatch =
      previousTask && typeof patch.note === "string" && taskHasUnfinishedSignal({ ...previousTask, ...patch })
        ? ({ status: "partial", completed: false } satisfies Partial<StudyTask>)
        : {};
    const normalizedPatch: Partial<StudyTask> = {
      ...patch,
      ...inferredPatch,
      ...(nextStatusFromPatch ? { completed: nextStatusFromPatch === "done" } : {})
    };
    const changedTaskTemplate = ["time", "subject", "title", "plannedMinutes"].some((field) => field in patch);
    const becameCompleted =
      Boolean(record.savedAt) &&
      previousTask &&
      normalizedPatch.status === "done" &&
      getTaskStatus(previousTask) !== "done";
    const pendingProgressTaskIds = becameCompleted
      ? [...new Set([...(record.pendingProgressTaskIds ?? []), taskId])]
      : record.pendingProgressTaskIds;
    onChange({
      ...record,
      tasks: record.tasks.map((task) =>
        task.id === taskId ? { ...task, ...normalizedPatch, ...(changedTaskTemplate ? { autoGenerated: false } : {}) } : task
      ),
      pendingProgressTaskIds,
      updatedAt: new Date().toISOString()
    });
  }

  function updateTaskStatus(taskId: string, status: TaskStatus) {
    updateTask(taskId, { status, completed: status === "done" });
  }

  function deleteTask(taskId: string) {
    if (!record) return;
    onChange({
      ...record,
      tasks: record.tasks.filter((task) => task.id !== taskId),
      updatedAt: new Date().toISOString()
    });
  }

  function addTask() {
    if (!record) return;
    const task: StudyTask = {
      id: uid("task"),
      date: record.date,
      time: "自定义",
      subject: "math",
      title: "自定义学习任务",
      plannedMinutes: 30,
      actualMinutes: 30,
      completed: false,
      status: "todo",
      quality: "",
      note: ""
    };
    onChange({ ...record, tasks: [...record.tasks, task], updatedAt: new Date().toISOString() });
  }

  function handleSave() {
    onSave();
    setSaveFeedbackAt(new Date().toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit", second: "2-digit" }));
  }

  function handleRegenerate() {
    const ok = window.confirm("这会用最新进度、昨日备注和剩余天数重排当前日期任务，并覆盖当前任务清单。继续吗？");
    if (!ok) return;
    onRegenerateRecord();
    setSaveFeedbackAt("");
  }

  return (
    <div className="page-shell">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <div className="flex flex-wrap items-center gap-2">
            <h2 className="text-2xl font-semibold">每日打卡 / 补打卡</h2>
            {record?.phase && <Badge className={phaseMeta[record.phase].badgeClass}>{phaseMeta[record.phase].shortLabel}</Badge>}
          </div>
          <p className="mt-1 text-sm text-muted-foreground">
            {displayDate(selectedDate)}，可补录任意一天的学习完成情况。
          </p>
        </div>
        <div className="flex flex-col gap-2 sm:flex-row sm:items-center">
          <Input type="date" value={selectedDate} onChange={(event) => onDateChange(event.target.value)} />
          {record ? (
            <div className="flex flex-col gap-1 sm:items-end">
              <div className="flex flex-col gap-2 sm:flex-row">
                <Button variant="outline" onClick={handleRegenerate}>
                  <RotateCcw className="h-4 w-4" />
                  按最新记录重排
                </Button>
                <Button onClick={handleSave}>
                  <Save className="h-4 w-4" />
                  {saveFeedbackAt ? "已保存" : record.savedAt ? "更新打卡" : "保存打卡"}
                </Button>
              </div>
              {(saveFeedbackAt || savedAtText) && (
                <p className="flex items-center gap-1 text-xs text-muted-foreground">
                  <CheckCircle2 className="h-3.5 w-3.5 text-emerald-600" />
                  {saveFeedbackAt ? `刚刚保存 ${saveFeedbackAt}` : `已保存 ${savedAtText}`}
                </p>
              )}
            </div>
          ) : (
            <Button onClick={onCreateRecord}>
              <Plus className="h-4 w-4" />
              生成该日任务
            </Button>
          )}
        </div>
      </div>

      {!record ? (
        <Card>
          <CardContent className="py-10 text-center">
            <p className="text-lg font-semibold">这一天还没有任务记录</p>
            <p className="mt-2 text-sm text-muted-foreground">
              点击“生成该日任务”后，可以补录当天完成情况并生成系统建议。
            </p>
            <Button className="mt-5" onClick={onCreateRecord}>
              <Plus className="h-4 w-4" />
              生成该日任务
            </Button>
          </CardContent>
        </Card>
      ) : (
      <div className="grid gap-4 lg:grid-cols-[0.72fr_1.28fr]">
        <div className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>今日完成情况</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <div className="mb-2 flex items-center justify-between text-sm">
                  <span className="font-medium">总完成率</span>
                  <span>{percent(completionRate)}</span>
                </div>
                <Progress value={completionRate} indicatorClassName="bg-orange-500" />
              </div>
              {stats
                .filter((stat) => stat.total > 0)
                .map((stat) => (
                  <div key={stat.subject}>
                    <div className="mb-2 flex items-center justify-between text-sm">
                      <Badge className={subjectMeta[stat.subject].badgeClass}>{subjectMeta[stat.subject].name}</Badge>
                  <span className="text-muted-foreground">
                        {stat.completed}完/{stat.partial}部分/{stat.total}项，{(stat.minutes / 60).toFixed(1)}小时
                      </span>
                    </div>
                    <Progress
                      value={stat.rate}
                      indicatorClassName={
                        stat.subject === "math"
                          ? "bg-blue-500"
                          : stat.subject === "cs408"
                            ? "bg-violet-500"
                            : stat.subject === "english"
                              ? "bg-emerald-500"
                              : "bg-orange-500"
                      }
                    />
                  </div>
                ))}
            </CardContent>
          </Card>

          {record.adjustmentMessages.length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle>今日调整依据</CardTitle>
              </CardHeader>
              <CardContent className="space-y-2">
                {record.adjustmentMessages.map((message) => (
                  <p key={message} className="rounded-lg bg-muted/50 p-2 text-sm text-muted-foreground">
                    {message}
                  </p>
                ))}
              </CardContent>
            </Card>
          )}

          <Card>
            <CardHeader>
              <CardTitle>今日总结</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              <Textarea
                value={record.summary}
                onChange={(event) =>
                  onChange({ ...record, summary: event.target.value, updatedAt: new Date().toISOString() })
                }
                placeholder="例如：数学积分部分不熟；操作系统进程同步较难；英语长难句翻译速度慢。"
              />
              {record.suggestion && (
                <div className="rounded-lg border border-orange-200 bg-orange-50 p-3 text-sm text-orange-800 dark:border-orange-900 dark:bg-orange-950/40 dark:text-orange-100">
                  <p className="font-medium">系统建议</p>
                  <p className="mt-1">{record.suggestion}</p>
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between gap-3">
            <CardTitle>任务清单</CardTitle>
            <Button variant="outline" size="sm" onClick={addTask}>
              <Plus className="h-4 w-4" />
              添加任务
            </Button>
          </CardHeader>
          <CardContent className="space-y-3">
            {sortedTasks.map((task) => (
              <div
                key={task.id}
                className={cn(
                  "rounded-lg border border-border border-l-4 bg-card p-3 transition",
                  subjectMeta[task.subject].borderClass,
                  isTaskDone(task) && "animate-complete bg-emerald-50/70 dark:bg-emerald-950/20",
                  isTaskPartial(task) && "bg-amber-50/70 dark:bg-amber-950/20"
                )}
              >
                <div className="grid gap-3 lg:grid-cols-[156px_112px_1fr_118px_96px_100px_40px] lg:items-center">
                  <div className="grid grid-cols-3 rounded-lg border border-border bg-muted/40 p-1" aria-label="任务完成状态">
                    {taskStatusOptions.map((option) => {
                      const active = getTaskStatus(task) === option.value;
                      return (
                        <button
                          key={option.value}
                          type="button"
                          title={option.title}
                          onClick={() => updateTaskStatus(task.id, option.value)}
                          className={cn(
                            "h-8 rounded-md px-2 text-xs font-medium transition",
                            active && option.value === "done" && "bg-emerald-600 text-white",
                            active && option.value === "partial" && "bg-amber-500 text-white",
                            active && option.value === "todo" && "bg-slate-600 text-white",
                            !active && "text-muted-foreground hover:bg-background"
                          )}
                        >
                          {option.label}
                        </button>
                      );
                    })}
                  </div>
                  <Input value={task.time} onChange={(event) => updateTask(task.id, { time: event.target.value })} />
                  <Input value={task.title} onChange={(event) => updateTask(task.id, { title: event.target.value })} />
                  <Select
                    value={task.subject}
                    onChange={(event) => updateTask(task.id, { subject: event.target.value as Subject })}
                  >
                    {subjectOptions.map((subject) => (
                      <option key={subject} value={subject}>
                        {subjectMeta[subject].name}
                      </option>
                    ))}
                  </Select>
                  <Input
                    type="number"
                    min={0}
                    value={task.actualMinutes}
                    onChange={(event) => updateTask(task.id, { actualMinutes: Number(event.target.value) })}
                    title="实际学习分钟数"
                  />
                  <Select
                    value={task.quality}
                    onChange={(event) => updateTask(task.id, { quality: event.target.value as Quality })}
                  >
                    {qualityOptions.map((quality) => (
                      <option key={quality || "empty"} value={quality}>
                        {quality || "质量"}
                      </option>
                    ))}
                  </Select>
                  <Button variant="ghost" size="icon" onClick={() => deleteTask(task.id)} title="删除任务">
                    <Trash2 className="h-4 w-4 text-muted-foreground" />
                  </Button>
                </div>
                <Input
                  className="mt-3"
                  value={task.note}
                  onChange={(event) => updateTask(task.id, { note: event.target.value })}
                  placeholder="单项备注，例如：还差2节课看完2.1章 / 第5讲没看完 / 阅读精读剩半篇"
                />
              </div>
            ))}
          </CardContent>
        </Card>
      </div>
      )}
    </div>
  );
}
