import { useEffect, useMemo, useRef, useState } from "react";
import { AppShell, PageKey } from "@/components/AppShell";
import { CheckinPage } from "@/components/CheckinPage";
import { Dashboard } from "@/components/Dashboard";
import { HistoryPage } from "@/components/HistoryPage";
import { ProgressPage } from "@/components/ProgressPage";
import { SettingsPage } from "@/components/SettingsPage";
import { StatsPage } from "@/components/StatsPage";
import { WeakPointsPage } from "@/components/WeakPointsPage";
import { PlanWorkspacePage } from "@/components/PlanWorkspacePage";
import { AppState, CustomStudyPlan, DailyRecord, ProgressState, Settings, StudyTask, WeakPoint } from "@/types/study";
import { addDays, todayKey } from "@/lib/date";
import {
  applyProgressFromRecord,
  createInitialState,
  ensureTodayRecord,
  extractWeakPointsFromRecord,
  generateDailyRecord,
  generateSuggestion,
  isTaskDone
} from "@/lib/studyData";
import { deletePersistedState, loadPersistedState, parseBackup, savePersistedState, serializeBackup } from "@/lib/storage";
import {
  getCloudUser,
  hasCloudConfig,
  pullStateFromCloud,
  pushStateToCloud,
  signInCloud,
  signOutCloud,
  signUpCloud
} from "@/lib/cloudSync";
import { uid } from "@/lib/utils";
import { AiTaskDraft } from "@/lib/aiPlanner";

function isUntouchedGeneratedRecord(record?: DailyRecord) {
  if (!record) return true;
  if (record.createdAt !== record.updatedAt) return false;
  if (record.savedAt || record.summary.trim() || record.suggestion.trim()) return false;

  return record.tasks.every(
    (task) =>
      task.autoGenerated &&
      !task.completed &&
      task.actualMinutes === task.plannedMinutes &&
      task.quality === "" &&
      task.note.trim() === ""
  );
}

function shouldRefreshGeneratedRecord(record: DailyRecord | undefined, createIfMissing = false) {
  if (!record) return createIfMissing;
  return isUntouchedGeneratedRecord(record);
}

function refreshGeneratedRecord(state: AppState, date: string, createIfMissing = false) {
  if (!shouldRefreshGeneratedRecord(state.records[date], createIfMissing)) return state;
  return {
    ...state,
    records: {
      ...state.records,
      [date]: generateDailyRecord(date, state)
    }
  };
}

function refreshTodayPlanIfUntouched(state: AppState) {
  return refreshGeneratedRecord(state, todayKey(), true);
}

function getCompletedTaskIds(record: DailyRecord) {
  return record.tasks.filter(isTaskDone).map((task) => task.id);
}

function getProgressTasksForSave(record: DailyRecord, firstSave: boolean) {
  if (firstSave) return record.tasks;

  const pendingIds = new Set(record.pendingProgressTaskIds ?? []);
  const appliedIds = new Set(record.progressAppliedTaskIds ?? []);
  const hasProgressMetadata = Boolean(record.progressAppliedTaskIds);
  const dirtySinceLastSave = Boolean(record.savedAt && record.updatedAt > record.savedAt);

  if (!hasProgressMetadata && dirtySinceLastSave) {
    if (pendingIds.size > 0) {
      return record.tasks.filter((task) => isTaskDone(task) && pendingIds.has(task.id));
    }
    return record.tasks;
  }

  return record.tasks.filter((task) => isTaskDone(task) && pendingIds.has(task.id) && !appliedIds.has(task.id));
}

function getNextProgressAppliedTaskIds(record: DailyRecord, firstSave: boolean, appliedTaskIds: string[]) {
  const hasProgressMetadata = Boolean(record.progressAppliedTaskIds);
  const dirtySinceLastSave = Boolean(record.savedAt && record.updatedAt > record.savedAt);
  const completedIds = getCompletedTaskIds(record);
  const nextIds = new Set(record.progressAppliedTaskIds ?? []);

  if (firstSave || (!hasProgressMetadata && dirtySinceLastSave)) {
    completedIds.forEach((id) => nextIds.add(id));
  } else if (!hasProgressMetadata) {
    completedIds.forEach((id) => nextIds.add(id));
  } else {
    appliedTaskIds.forEach((id) => nextIds.add(id));
  }

  return [...nextIds];
}

export default function App() {
  const [state, setState] = useState<AppState>(() => refreshTodayPlanIfUntouched(ensureTodayRecord(createInitialState())));
  const [hydrated, setHydrated] = useState(false);
  const [activePage, setActivePage] = useState<PageKey>("dashboard");
  const [cloudUserEmail, setCloudUserEmail] = useState<string | null>(null);
  const [cloudBusy, setCloudBusy] = useState(false);
  const [checkinDate, setCheckinDate] = useState(todayKey());
  const autoSyncFingerprintRef = useRef("");
  const today = todayKey();
  const checkinRecord = useMemo(() => state.records[checkinDate], [state.records, checkinDate]);
  const syncFingerprint = useMemo(
    () =>
      JSON.stringify({
        records: state.records,
        progress: state.progress,
        settings: state.settings,
        adjustmentLogs: state.adjustmentLogs,
        weakPoints: state.weakPoints,
        customPlans: state.customPlans
      }),
    [state.records, state.progress, state.settings, state.adjustmentLogs, state.weakPoints, state.customPlans]
  );

  useEffect(() => {
    let cancelled = false;

    loadPersistedState()
      .then((persistedState) => {
        if (cancelled) return;
        setState(refreshTodayPlanIfUntouched(ensureTodayRecord(persistedState)));
        setHydrated(true);
      })
      .catch(() => {
        if (cancelled) return;
        setState(ensureTodayRecord(createInitialState()));
        setHydrated(true);
      });

    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    if (!hydrated) return;
    void savePersistedState(state);
  }, [hydrated, state]);

  useEffect(() => {
    document.documentElement.classList.toggle("dark", state.settings.darkMode);
  }, [state.settings.darkMode]);

  useEffect(() => {
    if (!hasCloudConfig) return;
    void getCloudUser().then((user) => setCloudUserEmail(user?.email ?? null));
  }, []);

  useEffect(() => {
    if (!hydrated || !state.cloudSync.enabled || !state.cloudSync.autoSync || !cloudUserEmail || !hasCloudConfig) return;
    if (autoSyncFingerprintRef.current === syncFingerprint) return;

    const timer = window.setTimeout(() => {
      autoSyncFingerprintRef.current = syncFingerprint;
      pushCloudState("auto");
    }, 2500);

    return () => window.clearTimeout(timer);
  }, [hydrated, state.cloudSync.enabled, state.cloudSync.autoSync, cloudUserEmail, hasCloudConfig, syncFingerprint]);

  function updateRecord(date: string, record: DailyRecord) {
    setState((current) => ({
      ...current,
      records: {
        ...current.records,
        [date]: record
      }
    }));
  }

  function ensureRecordForDate(date: string) {
    setState((current) => {
      if (current.records[date]) return current;
      return {
        ...current,
        records: {
          ...current.records,
          [date]: generateDailyRecord(date, current)
        }
      };
    });
  }

  function regenerateRecordForDate(date: string) {
    setState((current) => ({
      ...current,
      records: {
        ...current.records,
        [date]: generateDailyRecord(date, current)
      }
    }));
  }

  function saveCheckin(date = checkinDate) {
    setState((current) => {
      const currentRecord = current.records[date];
      if (!currentRecord) return current;

      const now = new Date().toISOString();
      const suggestion = generateSuggestion(currentRecord);
      const firstSave = !currentRecord.savedAt;
      const draftSavedRecord: DailyRecord = {
        ...currentRecord,
        suggestion,
        phase: currentRecord.phase ?? current.settings.studyPhase,
        savedAt: now,
        updatedAt: now
      };
      const progressTasks = getProgressTasksForSave(currentRecord, firstSave);
      const appliedTaskIds = progressTasks.filter(isTaskDone).map((task) => task.id);
      const savedRecord: DailyRecord = {
        ...draftSavedRecord,
        progressAppliedTaskIds: getNextProgressAppliedTaskIds(currentRecord, firstSave, appliedTaskIds),
        pendingProgressTaskIds: []
      };
      const newWeakPoints = extractWeakPointsFromRecord(savedRecord, current.weakPoints);
      const nextProgress =
        progressTasks.length > 0
          ? applyProgressFromRecord(current.progress, { ...savedRecord, tasks: progressTasks })
          : current.progress;
      const nextWeakPoints = [...newWeakPoints, ...current.weakPoints].slice(0, 200);
      const nextRecords = {
        ...current.records,
        [date]: savedRecord
      };
      const shouldLogSuggestion = firstSave || suggestion !== currentRecord.suggestion;
      const nextAdjustmentLogs = shouldLogSuggestion
        ? [
            {
              id: uid("log"),
              date,
              message: suggestion,
              createdAt: now
            },
            ...current.adjustmentLogs
          ].slice(0, 80)
        : current.adjustmentLogs;

      const baseNextState: AppState = {
        ...current,
        progress: nextProgress,
        records: nextRecords,
        adjustmentLogs: nextAdjustmentLogs,
        weakPoints: nextWeakPoints
      };

      const refreshTargets = new Map<string, boolean>();
      const nextDate = addDays(date, 1);
      refreshTargets.set(nextDate, nextDate === today);
      refreshTargets.set(today, true);

      let nextState = baseNextState;
      for (const [refreshDate, createIfMissing] of [...refreshTargets.entries()].sort(([a], [b]) =>
        a.localeCompare(b)
      )) {
        if (refreshDate === date) continue;
        nextState = refreshGeneratedRecord(nextState, refreshDate, createIfMissing);
      }

      return nextState;
    });
  }

  function appendAiTasks(tasks: AiTaskDraft[]) {
    if (tasks.length === 0) return;
    const date = todayKey();
    setState((current) => {
      const record = current.records[date] ?? generateDailyRecord(date, current);
      const now = new Date().toISOString();
      const studyTasks: StudyTask[] = tasks.map((task) => ({
        id: uid("ai-task"),
        date,
        time: task.time || "自定义",
        subject: task.subject,
        title: task.title,
        plannedMinutes: task.plannedMinutes,
        completed: false,
        actualMinutes: task.plannedMinutes,
        quality: "",
        note: task.reason ? `DeepSeek建议：${task.reason}` : "",
        autoGenerated: false
      }));

      return {
        ...current,
        records: {
          ...current.records,
          [date]: {
            ...record,
            tasks: [...record.tasks, ...studyTasks],
            updatedAt: now
          }
        }
      };
    });
    setCheckinDate(date);
    setActivePage("checkin");
  }

  function updateProgress(progress: ProgressState) {
    setState((current) => refreshGeneratedRecord({ ...current, progress }, today, true));
  }

  function updateSettings(settings: Settings) {
    setState((current) => refreshGeneratedRecord({ ...current, settings }, today, true));
  }

  function updateCloudSync(patch: Partial<AppState["cloudSync"]>) {
    setState((current) => ({
      ...current,
      cloudSync: {
        ...current.cloudSync,
        ...patch
      }
    }));
  }

  function updateWeakPoints(weakPoints: WeakPoint[]) {
    setState((current) => ({ ...current, weakPoints }));
  }

  function updateCustomPlans(customPlans: CustomStudyPlan[]) {
    setState((current) => ({ ...current, customPlans }));
  }

  function resetState() {
    const fresh = ensureTodayRecord(createInitialState());
    void deletePersistedState();
    setState(fresh);
  }

  function exportBackup() {
    const blob = new Blob([serializeBackup(state)], { type: "application/json;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `考研打卡备份-${today}.json`;
    anchor.click();
    URL.revokeObjectURL(url);
  }

  async function importBackup(file: File) {
    try {
      const importedState = ensureTodayRecord(parseBackup(await file.text()));
      setState(importedState);
      setHydrated(true);
      await savePersistedState(importedState);
      window.alert("备份导入成功，当前数据已更新。");
    } catch {
      window.alert("备份导入失败，请确认选择的是本系统导出的 JSON 文件。");
    }
  }

  async function cloudSignUp(email: string, password: string) {
    setCloudBusy(true);
    try {
      const user = await signUpCloud(email, password);
      setCloudUserEmail(user?.email ?? email);
      updateCloudSync({ enabled: true, lastError: undefined });
      window.alert("注册成功。如果 Supabase 项目开启了邮箱验证，请先去邮箱完成验证后再登录。");
    } catch (error) {
      updateCloudSync({ lastError: error instanceof Error ? error.message : "注册失败" });
      window.alert("注册失败，数据仍会继续保存在本地。");
    } finally {
      setCloudBusy(false);
    }
  }

  async function cloudSignIn(email: string, password: string) {
    setCloudBusy(true);
    try {
      const user = await signInCloud(email, password);
      setCloudUserEmail(user?.email ?? email);
      updateCloudSync({ enabled: true, lastError: undefined });
      window.alert("登录成功。你可以手动上传本地数据到云端，或开启自动同步。");
    } catch (error) {
      updateCloudSync({ lastError: error instanceof Error ? error.message : "登录失败" });
      window.alert("登录失败，数据仍会继续保存在本地。");
    } finally {
      setCloudBusy(false);
    }
  }

  async function cloudSignOut() {
    setCloudBusy(true);
    try {
      await signOutCloud();
      setCloudUserEmail(null);
      updateCloudSync({ enabled: false, autoSync: false, lastError: undefined });
    } catch (error) {
      updateCloudSync({ lastError: error instanceof Error ? error.message : "退出登录失败" });
    } finally {
      setCloudBusy(false);
    }
  }

  async function pushCloudState(mode: "manual" | "auto" = "manual") {
    if (!hasCloudConfig || !cloudUserEmail) {
      updateCloudSync({ lastError: "尚未配置或登录 Supabase，无法同步到云端。" });
      return;
    }
    setCloudBusy(mode === "manual");
    try {
      const syncedAt = await pushStateToCloud(state);
      setState((current) => ({
        ...current,
        cloudSync: {
          ...current.cloudSync,
          enabled: true,
          lastSyncedAt: syncedAt,
          lastError: undefined
        }
      }));
      if (mode === "manual") window.alert("已上传到云端。本地数据仍会保留一份。");
    } catch (error) {
      setState((current) => ({
        ...current,
        cloudSync: {
          ...current.cloudSync,
          lastError: error instanceof Error ? error.message : "云同步失败，本地数据已保留。"
        }
      }));
      if (mode === "manual") window.alert("云端同步失败，但本地数据已经保存，不会丢失。");
    } finally {
      setCloudBusy(false);
    }
  }

  async function pullCloudState() {
    if (!hasCloudConfig || !cloudUserEmail) {
      updateCloudSync({ lastError: "尚未配置或登录 Supabase，无法从云端拉取。" });
      return;
    }
    const ok = window.confirm("从云端拉取会用云端快照覆盖当前浏览器数据。建议先导出本地备份。继续吗？");
    if (!ok) return;

    setCloudBusy(true);
    try {
      const result = await pullStateFromCloud();
      if (!result) {
        window.alert("云端还没有快照。你可以先点击“上传本地到云端”。");
        return;
      }
      const pulledAt = new Date().toISOString();
      const nextState = ensureTodayRecord({
        ...result.state,
        cloudSync: {
          ...result.state.cloudSync,
          enabled: true,
          autoSync: state.cloudSync.autoSync,
          lastPulledAt: pulledAt,
          lastError: undefined
        }
      });
      setState(nextState);
      await savePersistedState(nextState);
      window.alert("已从云端恢复数据，并同步保存到本地。");
    } catch (error) {
      updateCloudSync({ lastError: error instanceof Error ? error.message : "云端拉取失败，本地数据未改变。" });
      window.alert("云端拉取失败，本地数据没有被覆盖。");
    } finally {
      setCloudBusy(false);
    }
  }

  return (
    <AppShell
      activePage={activePage}
      darkMode={state.settings.darkMode}
      onNavigate={setActivePage}
      onToggleDark={() => updateSettings({ ...state.settings, darkMode: !state.settings.darkMode })}
    >
      {activePage === "dashboard" && <Dashboard state={state} onNavigate={setActivePage} onApplyAiTasks={appendAiTasks} />}
      {activePage === "checkin" && (
        <CheckinPage
          record={checkinRecord}
          selectedDate={checkinDate}
          onDateChange={(date) => {
            setCheckinDate(date);
            ensureRecordForDate(date);
          }}
          onCreateRecord={() => ensureRecordForDate(checkinDate)}
          onRegenerateRecord={() => regenerateRecordForDate(checkinDate)}
          onChange={(record) => updateRecord(checkinDate, record)}
          onSave={() => saveCheckin(checkinDate)}
        />
      )}
      {activePage === "history" && <HistoryPage state={state} />}
      {activePage === "progress" && (
        <ProgressPage state={state} onProgressChange={updateProgress} onSettingsChange={updateSettings} />
      )}
      {activePage === "weakness" && <WeakPointsPage state={state} onChange={updateWeakPoints} />}
      {activePage === "stats" && <StatsPage state={state} />}
      {activePage === "plans" && <PlanWorkspacePage plans={state.customPlans} onChange={updateCustomPlans} onNavigate={setActivePage} />}
      {activePage === "settings" && (
        <SettingsPage
          state={state}
          onSettingsChange={updateSettings}
          onProgressChange={updateProgress}
          onExportBackup={exportBackup}
          onImportBackup={importBackup}
          cloudConfigured={hasCloudConfig}
          cloudUserEmail={cloudUserEmail}
          cloudBusy={cloudBusy}
          onCloudSignUp={cloudSignUp}
          onCloudSignIn={cloudSignIn}
          onCloudSignOut={cloudSignOut}
          onCloudSyncChange={updateCloudSync}
          onPushCloud={() => pushCloudState("manual")}
          onPullCloud={pullCloudState}
          onReset={resetState}
        />
      )}
    </AppShell>
  );
}
